// flow-typed signature: beb522c2c9f3ed109e1fea060e54fcd6
// flow-typed version: <<STUB>>/import-jsx_v^1.3.0/flow_v0.72.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'import-jsx'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'import-jsx' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'import-jsx/index' {
  declare module.exports: $Exports<'import-jsx'>;
}
declare module 'import-jsx/index.js' {
  declare module.exports: $Exports<'import-jsx'>;
}
