// flow-typed signature: 16f9db63e742d509a181947828653a41
// flow-typed version: <<STUB>>/ink-select-input_v^2.0.0/flow_v0.92.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ink-select-input'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ink-select-input' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ink-select-input/dist/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ink-select-input/dist/index.js' {
  declare module.exports: $Exports<'ink-select-input/dist/index'>;
}
