// flow-typed signature: 8a42e37777d65de90a7ecd6960068dab
// flow-typed version: <<STUB>>/ink_v^0.5.1/flow_v0.90.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ink'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ink' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ink/lib/component' {
  declare module.exports: any;
}

declare module 'ink/lib/components/bold' {
  declare module.exports: any;
}

declare module 'ink/lib/components/br' {
  declare module.exports: any;
}

declare module 'ink/lib/components/color' {
  declare module.exports: any;
}

declare module 'ink/lib/components/div' {
  declare module.exports: any;
}

declare module 'ink/lib/components/indent' {
  declare module.exports: any;
}

declare module 'ink/lib/components/span' {
  declare module.exports: any;
}

declare module 'ink/lib/components/text' {
  declare module.exports: any;
}

declare module 'ink/lib/components/underline' {
  declare module.exports: any;
}

declare module 'ink/lib/diff' {
  declare module.exports: any;
}

declare module 'ink/lib/h' {
  declare module.exports: any;
}

declare module 'ink/lib/is-class-component' {
  declare module.exports: any;
}

declare module 'ink/lib/options' {
  declare module.exports: any;
}

declare module 'ink/lib/render-queue' {
  declare module.exports: any;
}

declare module 'ink/lib/render-to-string' {
  declare module.exports: any;
}

declare module 'ink/lib/renderer' {
  declare module.exports: any;
}

declare module 'ink/lib/string-component' {
  declare module.exports: any;
}

declare module 'ink/lib/transform-props' {
  declare module.exports: any;
}

declare module 'ink/lib/vnode' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ink/index' {
  declare module.exports: $Exports<'ink'>;
}
declare module 'ink/index.js' {
  declare module.exports: $Exports<'ink'>;
}
declare module 'ink/lib/component.js' {
  declare module.exports: $Exports<'ink/lib/component'>;
}
declare module 'ink/lib/components/bold.js' {
  declare module.exports: $Exports<'ink/lib/components/bold'>;
}
declare module 'ink/lib/components/br.js' {
  declare module.exports: $Exports<'ink/lib/components/br'>;
}
declare module 'ink/lib/components/color.js' {
  declare module.exports: $Exports<'ink/lib/components/color'>;
}
declare module 'ink/lib/components/div.js' {
  declare module.exports: $Exports<'ink/lib/components/div'>;
}
declare module 'ink/lib/components/indent.js' {
  declare module.exports: $Exports<'ink/lib/components/indent'>;
}
declare module 'ink/lib/components/span.js' {
  declare module.exports: $Exports<'ink/lib/components/span'>;
}
declare module 'ink/lib/components/text.js' {
  declare module.exports: $Exports<'ink/lib/components/text'>;
}
declare module 'ink/lib/components/underline.js' {
  declare module.exports: $Exports<'ink/lib/components/underline'>;
}
declare module 'ink/lib/diff.js' {
  declare module.exports: $Exports<'ink/lib/diff'>;
}
declare module 'ink/lib/h.js' {
  declare module.exports: $Exports<'ink/lib/h'>;
}
declare module 'ink/lib/is-class-component.js' {
  declare module.exports: $Exports<'ink/lib/is-class-component'>;
}
declare module 'ink/lib/options.js' {
  declare module.exports: $Exports<'ink/lib/options'>;
}
declare module 'ink/lib/render-queue.js' {
  declare module.exports: $Exports<'ink/lib/render-queue'>;
}
declare module 'ink/lib/render-to-string.js' {
  declare module.exports: $Exports<'ink/lib/render-to-string'>;
}
declare module 'ink/lib/renderer.js' {
  declare module.exports: $Exports<'ink/lib/renderer'>;
}
declare module 'ink/lib/string-component.js' {
  declare module.exports: $Exports<'ink/lib/string-component'>;
}
declare module 'ink/lib/transform-props.js' {
  declare module.exports: $Exports<'ink/lib/transform-props'>;
}
declare module 'ink/lib/vnode.js' {
  declare module.exports: $Exports<'ink/lib/vnode'>;
}
