// flow-typed signature: a051b04b802fcb7b35bd7af4078a8481
// flow-typed version: <<STUB>>/terminal-image_v^0.1.2/flow_v0.90.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'terminal-image'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'terminal-image' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'terminal-image/index' {
  declare module.exports: $Exports<'terminal-image'>;
}
declare module 'terminal-image/index.js' {
  declare module.exports: $Exports<'terminal-image'>;
}
